# Students
###
POST http://localhost:9000/api/students HTTP/1.1
Content-Type: application/json

{
    "name": "John",
    "lastName": "Doe",
    "email": "johndoe@example.com",
    "phone": "1234567890",
    "address": "123 Main Street",
    "age": 20,
    "gender": "male",
    "typeDocument": "passport",
    "typeSubject": "machine_learning",
    "numberDocument": "32832099203",
    "dateBirth": "2023-05-18"
}

###
GET http://localhost:9000/api/students HTTP/1.1

###
GET http://localhost:9000/api/students/6474f3eaa3bd9d59f1c8d86b HTTP/1.1

###
PUT  http://localhost:9000/api/students/6474f3eaa3bd9d59f1c8d86b HTTP/1.1
Content-Type: application/json

{
    "email": "john34@example.com"
}

###
DELETE  http://localhost:9000/api/students/6474f41b87a48f239b89d365 HTTP/1.1


# Teachers
### 
POST http://localhost:9000/api/teachers HTTP/1.1
Content-Type: application/json

{
    "name": "Jane",
    "lastName": "Smith",
    "email": "janesmith@example.com",
    "phone": "987654321",
    "address": "456 Elm St",
    "age": 20,
    "gender": "female",
    "typeDocument": "passport",
    "typeSubject": "machine_learning",
    "numberDocument": "1234567890",
    "dateBirth": "1987-05-10",
    "code": "AFDS23032S"
}

###
GET http://localhost:9000/api/teachers HTTP/1.1

###
GET http://localhost:9000/api/teachers/6475100a27d5bf42e04c4bc8 HTTP/1.1

###
PUT  http://localhost:9000/api/teachers/6474f3eaa3bd9d59f1c8d86b HTTP/1.1
Content-Type: application/json

{
    "email": "john34@example.com"
}

###
DELETE  http://localhost:9000/api/teachers/6475100a27d5bf42e04c4bc8 HTTP/1.1

